server:
  port: ${GRAPHQL_PORT:4000}

spring:
  graphql:
    path: ${GRAPHQL_PATH:/graphql}
    websocket:
      path: ${GRAPHQL_PATH:/subscription}
    graphiql:
      enabled: ${GRAPHQL_DASHBOARD:true}

redis:
  server: ${REDIS_HOST:localhost}
  port: ${REDIS_HOST:6379}
  password: ${REDIS_PASS:pass123}

logging:
  level:
    org:
      springframework:
        graphql: ${LOG_LEVEL:DEBUG}
    com:
      pmi:
        pmi40os: ${LOG_LEVEL:DEBUG}