apiVersion: v1
kind: Service
metadata:
  name: graphql-server
  labels:
    service: graphql-server
    service-type: backend
spec:
  ports:
  - name: ws
    port: 4000
    targetPort: 4000
  selector:
    service: graphql-server
    service-type: backend
  type: NodePort    
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-server-debug
  labels:
    service: graphql-server-debug
    service-type: backend
spec:
  ports:
    - name: jvm-debug
      protocol: TCP
      port: 4003
      targetPort: 4003
      nodePort: 32012
  selector:
    service: graphql-server
    service-type: backend
  type: NodePort